### ISSUE TITLE
Stage file removal fails with git 1.8

### ISSUE THREAD

**Issue by ablaagaard** [jupyterlab/jupyterlab-git#399]
I've delete a file and want to commit that.
When I click the stage icon nothing happens.
In the logs I see:

warning: You ran 'git add' with neither '-A (--all)' or '--ignore-removal',
whose behaviour will change in Git 2.0 with respect to paths you removed.
Paths like '<my file here>' that are
removed from your working tree are ignored with this version of Git.

My git version is 1.8.3.1 on Linux

**Comment by telamonian** [comment]
We made a lot of backend improvements in the latest version (`v0.9.0`). I've just tried this out, and I was able to correctly commit a deleted file.

@ablaagaard Can you please install the latest version of this plugin:

```
pip install -U jupyterlab-git
jupyter lab build
```

and then try commiting a deleted file again? It would be good to know whether we've fixed this, or if it's an issue with our support for [older versions of git](https://github.com/git/git/tags?after=v1.8.3.2)

**Comment by ablaagaard** [comment]
I upgraded, but still see the same issue:

[W 12:07:57.447 NotebookApp] delete /test4/test4.ipynb
[W 12:07:57.448 NotebookApp] Skipping trash for /opt/app-root/src/test4/test4.ipynb, on different device to home directory
warning: You ran 'git add' with neither '-A (--all)' or '--ignore-removal',
whose behaviour will change in Git 2.0 with respect to paths you removed.
Paths like 'test4.ipynb' that are
removed from your working tree are ignored with this version of Git.

* 'git add --ignore-removal <pathspec>', which is the current default,
  ignores paths you removed from your working tree.

* 'git add --all <pathspec>' will let you also record the removals.

Run 'git status' to check the paths you removed from your working tree.

**Comment by telamonian** [comment]
I'm going to close this for now as "won't fix". Git 2.0 has been out for almost 7 years, and I don't know if we're interested in trying to support versions of Git older than that.

If support for old versions is important to you, please feel free to submit a PR addressing the issue.
